---
title: "QTL Exploration: Specificity & Hotspots"
author: "sysgenAnalysis"
format: html
server: shiny
---

## Setup Environment

```{r}
#| context: setup
#| include: false
#| message: false
if (!requireNamespace("sysgenAnalysis", quietly = TRUE)) {
    devtools::install_github("AttieLab-Systems-Genetics/sysgenAnalysis")
}
```

## Results

### Summary

```{r}
DT::dataTableOutput("hotspots")
```

### Specificity Table

```{r}
DT::dataTableOutput("specificity")
```

### Interactive Manhattan Plot

```{r}
#| panel: sidebar
shiny::uiOutput("inputs")
```

```{r}
#| panel: fill
shiny::plotOutput("manhattan_plot", height = "600px")
```

```{r}
#| context: server

# Configuration
proj_root <- if (dir.exists("byandell/output")) "." else "../.."
save_dir <- file.path(proj_root, "byandell/output")
output_path <- file.path(save_dir, "QTL_Differential_Analysis")

# Load Results from CSVs
qtl_res <- sysgenAnalysis::read_qtl_analysis(output_path)

output$hotspots <- DT::renderDataTable({
  summary(qtl_res, type = "hotspots")
})

output$specificity <- DT::renderDataTable({
  if (!is.null(qtl_res$summary_table)) {
    summary(qtl_res, type = "specificity")
  } else {
    NULL
  }
})

output$inputs <- shiny::renderUI({
  all_chrs <- levels(reorder(qtl_res$plot_data$qtl_chr,
                             qtl_res$plot_data$cum_pos))
  all_classes <- unique(qtl_res$plot_data$trait_class)
  max_lod <- max(qtl_res$top_10_hs$max_lod)

  shiny::tagList(
    shiny::checkboxGroupInput("chrs", "Select Chromosomes:",
      choices = all_chrs, selected = all_chrs, inline = TRUE),
    shiny::checkboxGroupInput("classes", "Select Trait Classes:",
      choices = all_classes, selected = all_classes),
    shiny::sliderInput("lod", "Minimum LOD Score:",
      min = 0, max = floor(max_lod), value = 7, step = 1)
  )
})

output$manhattan_plot <- renderPlot({
  plot(qtl_res, 
       chr = input$chrs, 
       trait_class = input$classes, 
       lod_thresh = input$lod)
})
```
