# Link to shared infrastructure (removed for package structure)

#' Load and Filter Trans-eQTLs
#'
#' Reads a peak summary CSV file and filters for trans-eQTLs (cis == FALSE).
#' Automatically converts genomic positions to Mb if necessary.
#'
#' @param dir Directory where the file is located.
#' @param filename Name of the peak summary CSV file.
#' @param group_label A string label for the group (e.g., "High Fat").
#'
#' @return A tibble containing trans-eQTL peaks with columns: qtl_chr, qtl_pos, gene_symbol, and Group.
#'
#' @importFrom data.table fread
#' @importFrom tibble as_tibble
#' @importFrom dplyr filter mutate if_else select
#' @export
load_trans_eqtls <- function(dir, filename, group_label) {
  path <- file.path(dir, filename)
  if (!file.exists(path)) {
    warning(paste("File not found:", path))
    return(NULL)
  }

  df <- data.table::fread(path) |>
    tibble::as_tibble() |>
    dplyr::filter(cis == FALSE)

  # Ensure positions are in Mb if they look like bp
  if (nrow(df) > 0 && max(df$qtl_pos, na.rm = TRUE) > 10000) {
    df$qtl_pos <- df$qtl_pos / 1e6
  }

  df <- df |>
    dplyr::select(qtl_chr, qtl_pos, gene_symbol) |>
    dplyr::mutate(group = group_label)

  return(df)
}

#' Calculate Hotspot Density
#'
#' Counts the number of eQTLs in a sliding window across the genome.
#'
#' @param data A data frame containing trans-eQTL results (must have qtl_chr and qtl_pos).
#' @param window_size_mb Width of the sliding window in Mb (default 1).
#' @param step_mb Distance the window slides in each step in Mb (default 0.5).
#'
#' @return A tibble with columns: qtl_chr, pos_mb, and count.
#'
#' @importFrom dplyr filter bind_rows
#' @importFrom tibble tibble
#' @export
calculate_hotspot_density <- function(data, window_size_mb = 1, step_mb = 0.5) {
  results <- list()

  # Ensure chromosomes are handled as factors or specific order
  chrs <- unique(data$qtl_chr)

  for (chr in chrs) {
    chr_data <- data |> dplyr::filter(qtl_chr == chr)
    if (nrow(chr_data) == 0) next

    max_pos <- max(chr_data$qtl_pos, na.rm = TRUE)
    # Create sliding window centers
    windows <- seq(0, max_pos, by = step_mb)

    counts <- sapply(windows, function(w_center) {
      sum(chr_data$qtl_pos >= (w_center - window_size_mb / 2) &
        chr_data$qtl_pos < (w_center + window_size_mb / 2))
    })

    results[[as.character(chr)]] <- tibble::tibble(
      qtl_chr = chr,
      pos_mb = windows,
      count = counts
    )
  }

  return(dplyr::bind_rows(results))
}

#' Plot Hotspot Density
#'
#' Visualizes the trans-eQTL count across chromosomes using a line plot.
#'
#' @param density_data Data frame generated by `calculate_hotspot_density`.
#' @param title Plot title.
#'
#' @return A ggplot object.
#'
#' @importFrom ggplot2 ggplot aes geom_line facet_wrap theme_minimal labs theme element_rect
#' @export
plot_hotspots <- function(density_data, title) {
  # Clean up chromosome levels for plotting using common helper
  density_data$qtl_chr <- clean_chr_factor(density_data$qtl_chr)

  p <- ggplot2::ggplot(density_data, ggplot2::aes(x = pos_mb, y = count, color = group)) +
    ggplot2::geom_line(linewidth = 0.8) +
    ggplot2::facet_wrap(~qtl_chr, scales = "free_x", nrow = 2) +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = title,
      x = "Genomic Position (Mb)",
      y = "Trans-eQTL Count (1Mb Window)",
      color = "Group"
    ) +
    ggplot2::theme(
      legend.position = "bottom",
      strip.background = ggplot2::element_rect(fill = "grey90")
    )

  return(p)
}

#' Find Differential Hotspots
#'
#' Identifies regions where the difference in eQTL density between two groups
#' exceeds a specified threshold.
#'
#' @param density_data Combined density data for at least two groups.
#' @param raw_data Master trans-eQTL data frame containing phenotype/gene details.
#' @param threshold Minimum difference in count to consider a hotspot "differential".
#'
#' @return A data frame containing the traits mapping to the differential hotspot regions.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr mutate filter arrange desc bind_rows distinct
#' @export
find_differential_hotspots <- function(density_data, raw_data, threshold = 10) {
  # 1. Pivot data to compare groups side-by-side
  comparison <- density_data |>
    tidyr::pivot_wider(names_from = group, values_from = count, values_fill = 0)

  # Get group names dynamically
  groups <- unique(density_data$group)
  col1 <- groups[1]
  col2 <- groups[2]

  # 2. Calculate difference
  diff_hotspots <- comparison |>
    dplyr::mutate(diff = abs(.data[[col1]] - .data[[col2]])) |>
    dplyr::filter(diff >= threshold) |>
    dplyr::arrange(dplyr::desc(diff))

  if (nrow(diff_hotspots) == 0) {
    return(NULL)
  }

  # 3. Extract traits mapping to these windows
  mapping_traits <- list()

  for (i in seq_len(nrow(diff_hotspots))) {
    row <- diff_hotspots[i, ]

    traits <- raw_data |>
      dplyr::filter(
        qtl_chr == row$qtl_chr,
        qtl_pos >= (row$pos_mb - 0.5), # matches 1Mb window logic
        qtl_pos <= (row$pos_mb + 0.5)
      ) |>
      dplyr::mutate(
        hotspot_region = paste0("Chr", row$qtl_chr, ":", row$pos_mb, "Mb"),
        diff_score = row$diff
      )

    mapping_traits[[i]] <- traits
  }

  return(dplyr::bind_rows(mapping_traits) |> dplyr::distinct())
}

#' Plot Differential Hotspots
#'
#' Creates a bar plot showing the difference in eQTL density between two groups.
#'
#' @param density_data Combined density data for two groups.
#' @param group_names A vector of two group names (e.g., c("Female", "Male")).
#' @param title Plot title.
#'
#' @return A ggplot object.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr mutate
#' @importFrom ggplot2 ggplot aes geom_col geom_hline facet_wrap theme_minimal scale_fill_manual labs theme element_rect
#' @export
plot_differential_hotspots <- function(density_data, group_names, title) {
  # Pivot to calculate the difference
  diff_plot_data <- density_data |>
    tidyr::pivot_wider(names_from = group, values_from = count, values_fill = 0) |>
    dplyr::mutate(
      diff = .data[[group_names[1]]] - .data[[group_names[2]]],
      Dominant_Group = ifelse(diff > 0, group_names[1], group_names[2])
    )

  # Clean up chromosome levels using common helper
  diff_plot_data$qtl_chr <- clean_chr_factor(diff_plot_data$qtl_chr)

  p <- ggplot2::ggplot(diff_plot_data, ggplot2::aes(x = pos_mb, y = diff, fill = Dominant_Group)) +
    ggplot2::geom_col(width = 0.5) + # Bars make the "magnitude" of difference very clear
    ggplot2::geom_hline(yintercept = 0, linetype = "dashed", color = "grey50") +
    ggplot2::facet_wrap(~qtl_chr, scales = "free_x", nrow = 2) +
    ggplot2::theme_minimal() +
    ggplot2::scale_fill_manual(values = c(
      "Female" = "#e41a1c", "Male" = "#377eb8",
      "High Carbohydrate" = "#4daf4a", "High Fat" = "#984ea3",
      "High Fat Diet" = "#984ea3", "High Carbohydrate Diet" = "#4daf4a"
    )) +
    ggplot2::labs(
      title = title,
      subtitle = paste(group_names[1], "(+) vs", group_names[2], "(-)"),
      x = "Genomic Position (Mb)",
      y = "Difference in Trans-eQTL Count",
      fill = "Higher Density In:"
    ) +
    ggplot2::theme(
      legend.position = "bottom",
      strip.background = ggplot2::element_rect(fill = "grey95")
    )

  return(p)
}

#' Run Comprehensive Trans-eQTL Hotspot Analysis
#'
#' Automates data loading, density calculation, differential analysis, and visualization.
#'
#' @param phenotype_classes Character vector of phenotype classes to analyze.
#' @param qtl_model QTL model used (e.g., "additive").
#' @param input_dir Directory containing peak summary CSV files.
#' @param groups Character vector of groups (default c("HC", "HF", "female", "male")).
#' @param window_size_mb Window size for density calculation (default 1).
#' @param step_mb Step size for density calculation (default 0.5).
#' @param threshold Threshold for identifying differential hotspots (default 15).
#'
#' @return An object of class `hotspot_analysis`.
#'
#' @importFrom dplyr bind_rows group_by do
#' @importFrom readr write_csv
#' @export
run_hotspot_analysis <- function(phenotype_classes,
                                 qtl_model = "additive",
                                 input_dir,
                                 groups = c("HC", "HF", "female", "male"),
                                 window_size_mb = 1,
                                 step_mb = 0.5,
                                 threshold = 15) {
  all_results <- list()

  for (t_class in phenotype_classes) {
    message("Processing Hotspots for Trait Class: ", t_class)
    class_res <- list()

    # --- Process DIET ---
    if (all(c("HC", "HF") %in% groups)) {
      message("  Processing Diet Hotspots...")
      diet_data <- dplyr::bind_rows(
        load_trans_eqtls(input_dir, paste0("DO1200_", t_class, "_HF_mice_", qtl_model, "_peaks.csv"), "High Fat"),
        load_trans_eqtls(input_dir, paste0("DO1200_", t_class, "_HC_mice_", qtl_model, "_peaks.csv"), "High Carbohydrate")
      )

      if (nrow(diet_data) > 0) {
        diet_density <- diet_data |>
          dplyr::group_by(group) |>
          dplyr::do(calculate_hotspot_density(., window_size_mb = window_size_mb, step_mb = step_mb))

        diet_diff_traits <- find_differential_hotspots(diet_density, diet_data, threshold = threshold)

        class_res$diet <- list(
          density = diet_density,
          diff_traits = diet_diff_traits
        )
      }
    }

    # --- Process SEX ---
    if (all(c("female", "male") %in% groups)) {
      message("  Processing Sex Hotspots...")
      sex_data <- dplyr::bind_rows(
        load_trans_eqtls(input_dir, paste0("DO1200_", t_class, "_male_mice_", qtl_model, "_peaks.csv"), "Male"),
        load_trans_eqtls(input_dir, paste0("DO1200_", t_class, "_female_mice_", qtl_model, "_peaks.csv"), "Female")
      )

      if (nrow(sex_data) > 0) {
        sex_density <- sex_data |>
          dplyr::group_by(group) |>
          dplyr::do(calculate_hotspot_density(., window_size_mb = window_size_mb, step_mb = step_mb))

        sex_diff_traits <- find_differential_hotspots(sex_density, sex_data, threshold = threshold)

        class_res$sex <- list(
          density = sex_density,
          diff_traits = sex_diff_traits
        )
      }
    }

    all_results[[t_class]] <- class_res
  }

  res <- list(
    results = all_results,
    params = list(
      phenotype_classes = phenotype_classes,
      groups = groups,
      threshold = threshold,
      window_size_mb = window_size_mb,
      step_mb = step_mb
    )
  )
  class(res) <- "hotspot_analysis"

  message("Hotspot analysis complete.")
  return(res)
}

#' Print Hotspot Analysis Result
#'
#' @param x An object of class `hotspot_analysis`.
#' @param ... Extra arguments (ignored).
#'
#' @export
print.hotspot_analysis <- function(x, ...) {
  cat("Hotspot Analysis Result Object\n")
  cat("------------------------------\n")
  cat("Trait Classes: ", paste(x$params$phenotype_classes, collapse = ", "), "\n")
  cat("Groups:        ", paste(x$params$groups, collapse = ", "), "\n")
  cat("Threshold:     ", x$params$threshold, "\n")
}

#' Summary of Hotspot Analysis
#'
#' @param object An object of class `hotspot_analysis`.
#' @param ... Extra arguments (ignored).
#'
#' @return A list of differential hotspot traits.
#'
#' @export
summary.hotspot_analysis <- function(object, ...) {
  summaries <- list()
  for (t_class in names(object$results)) {
    class_res <- object$results[[t_class]]
    if (!is.null(class_res$diet$diff_traits)) {
      summaries[[paste0(t_class, "_diet")]] <- class_res$diet$diff_traits
    }
    if (!is.null(class_res$sex$diff_traits)) {
      summaries[[paste0(t_class, "_sex")]] <- class_res$sex$diff_traits
    }
  }
  return(summaries)
}

#' Plot Hotspot Analysis
#'
#' @param x An object of class `hotspot_analysis`.
#' @param ... Extra arguments (passed to plotting functions).
#'
#' @return A list of ggplot objects.
#'
#' @export
plot.hotspot_analysis <- function(x, ...) {
  plots <- list()
  for (t_class in names(x$results)) {
    class_res <- x$results[[t_class]]

    if (!is.null(class_res$diet$density)) {
      plots[[paste0(t_class, "_diet_density")]] <- plot_hotspots(
        class_res$diet$density, paste("Trans-eQTL Hotspots by Diet:", t_class)
      )
      plots[[paste0(t_class, "_diet_diff")]] <- plot_differential_hotspots(
        class_res$diet$density,
        group_names = c("High Carbohydrate", "High Fat"),
        title = paste("Differential eQTL Hotspots: HC vs HF (", t_class, ")")
      )
    }

    if (!is.null(class_res$sex$density)) {
      plots[[paste0(t_class, "_sex_density")]] <- plot_hotspots(
        class_res$sex$density, paste("Trans-eQTL Hotspots by Sex:", t_class)
      )
      plots[[paste0(t_class, "_sex_diff")]] <- plot_differential_hotspots(
        class_res$sex$density,
        group_names = c("Female", "Male"),
        title = paste("Differential eQTL Hotspots: Female vs Male (", t_class, ")")
      )
    }
  }
  return(plots)
}
